import random
from unicodedata import category
from django.template.defaultfilters import slugify
from django.core.management import BaseCommand
from account.models import Store, UserAccount 
from store.models import Product, Category, SubCategory, Brand
from decimal  import Decimal

PRODUCTS = [
        {
            "name": "Hp Notebook 14 - DQ0032DX",
            "vendor": "2",
            "title": "Hp Notebook 14 - DQ0032DX",
            "slug": "hp-notebook-14---dq0032dx",
            "description": "More Information\r\nProduct Type Laptop\r\nAvailability In Stock\r\nSeries HP. Notebook\r\nModel dq0032dx\r\nOS Version Windows 11 Home\r\nProcessor Intel Celeron\r\nGeneration Dual Core\r\nSpeed 1.1 / 2.8 Ghz, N4020, 4MB Cache, 2 Core, 2 Thread\r\nScreen Size 14\"\r\nMax Res 1366 x 768 :HD\r\nDetail micro-edge, BrightView, 220 nits, 45% NTSC\r\nRAM 4 GB\r\nDrive 64 GB\r\nType eMMC\r\nOptical No Optical Drive\r\nGraphics Card Intel Integrated Graphics\r\nMemory System Shared\r\nAudio Dual speakers\r\nFeatures Wifi, WebCam, Bluetooth\r\nExternal Ports USB 3.x, HDMI, Headphone/Mic combo, USB-C\r\nDimensions 32.4 x 22.5 x 1.79 cm\r\nWeight 3.218 lbs\r\nManufacturer Link Additional Information\r\nWarranty International / Manufacturer\r\nColor White",
            "discount": "0",
            "disc_value": "0",
            "disc_price": "0",
            "category": "laptop",
            "sub_category": "notebook",
            "brands": "hp",
            "price": "58500",
            "quantity": "15",
            "image": "https://myshop.pk/pub/media/catalog/product/cache/044822f421975447750ae9c7b18ed8ed/h/p/hp-14-dq0032dx-white-myshop-pk-1.jpg"
        },
        {
            "name": "Hp Notebook 14 - DQ0032DX UG",
            "vendor": "2",
            "title": "Hp Notebook 14 - DQ0032DX UG",
            "slug": "hp-notebook-14---dq0032dx-ug",
            "description": "More Information\r\nProduct Type Laptop\r\nAvailability In Stock\r\nSeries HP. Notebook\r\nModel dq0032dx\r\nOS Version Windows 11 Home\r\nProcessor Intel Celeron\r\nGeneration Dual Core\r\nSpeed 1.1 / 2.8 Ghz, N4020, 4MB Cache, 2 Core, 2 Thread\r\nScreen Size 14\"\r\nMax Res 1366 x 768 :HD\r\nDetail micro-edge, BrightView, 220 nits, 45% NTSC\r\nRAM 4 GB\r\nDrive 64 GB\r\nType eMMC\r\nAdditional 256GB SD Card\r\nDetail 256GB MicroSD Card will be added in External Memory Card Slot\r\nOptical No Optical Drive\r\nGraphics Card Intel Integrated Graphics\r\nMemory System Shared\r\nAudio Dual speakers\r\nFeatures Wifi, WebCam, Bluetooth\r\nExternal Ports USB 3.x, HDMI, Headphone/Mic combo, USB-C\r\nDimensions 32.4 x 22.5 x 1.79 cm\r\nWeight 3.218 lbs\r\nManufacturer Link Additional Information\r\nWarranty International / Manufacturer\r\nColor White",
            "discount": "0",
            "disc_value": "0",
            "disc_price": "0",
            "category": "laptop",
            "sub_category": "notebook",
            "brands": "hp",
            "price": "62900",
            "quantity": "59",
            "image": "https://myshop.pk/pub/media/catalog/product/cache/044822f421975447750ae9c7b18ed8ed/h/p/hp-14-dq0032dx-white-myshop-pk-1_1.jpg"
        },
        {
            "name": "Hp Notebook 15s - DU1520TU",
            "vendor": "0",
            "title": "Hp Notebook 15s - DU1520TU",
            "slug": "hp-notebook-15s---du1520tu",
            "description": "More Information\r\nProduct Type Laptop\r\nAvailability Same Day Delivery\r\nSeries HP. Notebook\r\nModel DU1520TU (465S5PA)\r\nOS Version Windows 10 Home\r\nProcessor Intel Celeron\r\nGeneration 1st Generation\r\nSpeed 1.1 / 2.8 Ghz, N4020, 4MB Cache, 2 Core, 2 Thread\r\nDetail Intel® Celeron® N4020 (1.1 GHz base frequency, up to 2.8 GHz burst frequency, 4 MB L2 cache, 2 cores)\r\nScreen Size 15.6\"\r\nMax Res 1366 x 768 :HD\r\nDetail 15.6\" diagonal, HD (1366 x 768), micro-edge, BrightView, 220 nits, 45% NTSC\r\nRAM 4 GB\r\nDetail 4 GB DDR4-2400 MHz RAM (1 x 4 GB)\r\nDrive 1 TB\r\nType HDD\r\nDetail 1 TB 5400 rpm SATA HDD\r\nOptical No Optical Drive\r\nGraphics Card Intel Integrated Graphics\r\nMemory System Shared\r\nDetail Intel® UHD Graphics 600\r\nFeatures Wifi, WebCam, Bluetooth\r\nExternal Ports USB 3.x, HDMI, RJ45 (LAN), Headphone/Mic combo, USB-C\r\nTotal USB 2\r\nDimensions 35.85 x 24.2 x 1.99 cm\r\nWeight 3.92 lbs\r\nManufacturer Link Additional Information\r\nWarranty 1 Year Local\r\nColor Silver",
            "discount": "1",
            "disc_value": "15",
            "disc_price": "11025",
            "category": "laptop",
            "sub_category": "notebook",
            "brands": "hp",
            "price": "73500",
            "quantity": "57",
            "image": "https://myshop.pk/pub/media/catalog/product/cache/044822f421975447750ae9c7b18ed8ed/h/p/hp_notebook_15_-_dy2071wm_myshop-pk-1_1_1_1_12.jpg"
        },
        {
            "name": "Hp Notebook 14 - DQ2031tg",
            "vendor": "0",
            "title": "Hp Notebook 14 - DQ2031tg",
            "slug": "hp-notebook-14---dq2031tg",
            "description": "More Information\r\nExtra Value with 4Core Processor, FullHD Screen & Fingerprint\r\nProduct Type Laptop\r\nAvailability Sold Out\r\nSeries HP. Notebook\r\nModel DQ2031tg (333V2UA)\r\nOS Version Windows 10 Home in S Mode\r\nProcessor Intel Core i3\r\nGeneration 11th Generation\r\nSpeed 2.0 / 3.7 Ghz, i3-1125G4, 8MB Cache, 4 Core, 8 Thread\r\nScreen Size 14\"\r\nMax Res 1920 x 1080 :Full HD\r\nDetail 35.6 cm (14\") diagonal, FHD (1920 x 1080), IPS, micro-edge, anti-glare, 250 nits, 45% NTSC\r\nRAM 4 GB\r\nDetail 4 GB DDR4-2666 MHz RAM (1 x 4 GB)\r\nDrive 128 GB\r\nType SSD\r\nDetail 128 GB SATA 3 TLC M.2 SSD\r\nOptical No Optical Drive\r\nGraphics Card Intel Integrated Graphics\r\nMemory System Shared\r\nDetail Intel® UHD Graphics\r\nAudio HD Audio with stereo speakers\r\nFeatures Wifi, WebCam, Bluetooth, Fingerprint Reader\r\nExternal Ports USB 3.0, HDMI, Headphone/Mic combo, USB-C\r\nTotal USB 2\r\nDimensions 12.76 x 8.86 x 0.71 in\r\nWeight 3.24 lb\r\nManufacturer Link Additional Information\r\nWarranty International / Manufacturer\r\nColor Silver",
            "discount": "0",
            "disc_value": "0",
            "disc_price": "0",
            "category": "laptop",
            "sub_category": "notebook",
            "brands": "hp",
            "price": "87500",
            "quantity": "82",
            "image": "https://myshop.pk/pub/media/catalog/product/cache/044822f421975447750ae9c7b18ed8ed/7/1/71tc1jqtois.-ac-sl1500--4012-720176-081221123603028-myshop-pk-1.jpg"
        },
        {
            "name": "Hp Notebook 15 - FQ2002NE",
            "vendor": "2",
            "title": "Hp Notebook 15 - FQ2002NE",
            "slug": "hp-notebook-15---fq2002ne",
            "description": "More Information\r\nProduct Type Laptop\r\nAvailability Coming Soon\r\nSeries HP. Notebook\r\nModel fq2002ne\r\nOS Version Windows 10 Home\r\nProcessor Intel Core i3\r\nGeneration 11th Generation\r\nSpeed 1.7 / 4.1 Ghz, i3-1115G4, 6MB Cache, 2 Core, 4 Thread\r\nScreen Size 15.6\"\r\nMax Res 1366 x 768 :HD\r\nDetail 39.6 cm (15.6\") diagonal, HD (1366 x 768), micro-edge, anti-glare, 250 nits, 45% NTSC\r\nRAM 4 GB\r\nDrive 128 GB\r\nType SSD\r\nOptical No Optical Drive\r\nGraphics Card Intel Integrated Graphics\r\nMemory System Shared\r\nFeatures Wifi, WebCam, Bluetooth\r\nExternal Ports USB 3.x, HDMI, Headphone/Mic combo, USB-C, Card Slot\r\nDimensions 35.85 x 24.2 x 1.79 cm\r\nWeight 3.858 lbs\r\nManufacturer Link Additional Information\r\nWarranty International / Manufacturer\r\nColor Black",
            "discount": "1",
            "disc_value": "15",
            "disc_price": "13125",
            "category": "laptop",
            "sub_category": "notebook",
            "brands": "hp",
            "price": "87500",
            "quantity": "25",
            "image": "https://myshop.pk/pub/media/catalog/product/cache/044822f421975447750ae9c7b18ed8ed/h/p/hp-notebook-15-dw3157nia-myshop-pk-1_1.jpg"
        },
        {
            "name": "Dell Inspiron 15 - 3511 i3 :1y",
            "vendor": "0",
            "title": "Dell Inspiron 15 - 3511 i3 :1y",
            "slug": "dell-inspiron-15---3511-i3-:1y",
            "description": "More Information\r\nProduct Type Laptop\r\nAvailability In Stock\r\nSeries Dell. Inspiron\r\nModel 3511 (3000)\r\nOS Version DOS\r\nProcessor Intel Core i3\r\nGeneration 11th Generation\r\nSpeed 1.7 / 4.1 Ghz, i3-1115G4, 6MB Cache, 2 Core, 4 Thread\r\nScreen Size 15.6\"\r\nMax Res 1920 x 1080 :Full HD\r\nDetail 15.6-inch FHD (1920 x 1080) Anti-glare LED Backlight Non-Touch Narrow Border WVA Display\r\nRAM 4 GB\r\nDrive 1 TB\r\nType HDD\r\nOptical No Optical Drive\r\nGraphics Card Intel Integrated Graphics\r\nMemory System Shared\r\nFeatures Wifi, WebCam, Bluetooth\r\nExternal Ports USB 2.0, USB 3.x, HDMI, Headphone/Mic combo, Card Slot\r\nDimensions Height (front): 17.50 mm (0.68\") x Height (rear): 18.99 mm (0.74\") x Width: 358.50 mm (14.11\") x Depth: 235.56 (9.27\")\r\nWeight 1.85 kg / 4.07 lb\r\nManufacturer Link Additional Information\r\nWarranty 1 Year Local\r\nColor Black\r\nColor Detail Carbon Black",
            "discount": "0",
            "disc_value": "0",
            "disc_price": "0",
            "category": "laptop",
            "sub_category": "notebook",
            "brands": "dell",
            "price": "88500",
            "quantity": "85",
            "image": "https://myshop.pk/pub/media/catalog/product/cache/26f8091d81cea4b38d820a1d1a4f62be/d/e/dell-inspiron-3511-black-1-myshop-pk-1_2_1.jpg"
        },
        {
            "name": "Dell Vostro 14 - 3400",
            "vendor": "0",
            "title": "Dell Vostro 14 - 3400",
            "slug": "dell-vostro-14---3400",
            "description": "More Information\r\nProduct Type Laptop\r\nAvailability In Stock\r\nSeries Dell. Vostro\r\nModel 3400\r\nOS Version DOS\r\nProcessor Intel Core i5\r\nGeneration 11th Generation\r\nSpeed 2.4 / 4.2 Ghz, i5-1135G7, 8MB Cache, 4 Core, 8 Thread\r\nScreen Size 14\"\r\nMax Res 1920 x 1080 :Full HD\r\nDetail 14\", FHD 1920x1080, 60Hz, Non-Touch, AG, Wide Viewing Angle, LED-Backlit, Narrow Border\r\nRAM 8 GB\r\nDrive 1 TB\r\nType HDD\r\nOptical No Optical Drive\r\nGraphics Card Intel Integrated Graphics\r\nMemory System Shared\r\nFeatures Wifi, WebCam, Bluetooth\r\nExternal Ports USB 2.0, USB 3.x, HDMI, RJ45 (LAN), Headphone/Mic combo, Card Slot\r\nDimensions 328 x 239.5 x 18.1-19 mm\r\nWeight 3.51 lbs\r\nManufacturer Link Additional Information\r\nWarranty International / Manufacturer\r\nColor Black\r\nColor Detail Accent Black",
            "discount": "0",
            "disc_value": "0",
            "disc_price": "0",
            "category": "laptop",
            "sub_category": "notebook",
            "brands": "dell",
            "price": "110500",
            "quantity": "8",
            "image": "https://myshop.pk/pub/media/catalog/product/cache/26f8091d81cea4b38d820a1d1a4f62be/d/e/dell-vostor-14-3400-myshop-pk-1.jpg"
        },
        {
            "name": "Dell Latitude - 3520 :1y",
            "vendor": "2",
            "title": "Dell Latitude - 3520 :1y",
            "slug": "dell-latitude---3520-:1y",
            "description": "More Information\r\nProduct Type Laptop\r\nAvailability Same Day Delivery\r\nSeries Dell. Latitude\r\nModel 3520\r\nOS Version DOS\r\nProcessor Intel Core i3\r\nGeneration 11th Generation\r\nSpeed 1.7 / 4.1 Ghz, i3-1115G4, 6MB Cache, 2 Core, 4 Thread\r\nScreen Size 15.6\"\r\nMax Res 1920 x 1080 :Full HD\r\nDetail 15.6\" FHD (1920 x 1080) AG Non-Touch, 250nits, Camera w/shutter & Microphone, WLAN Capable\r\nRAM 8 GB\r\nDrive 256 GB\r\nType SSD\r\nOptical No Optical Drive\r\nGraphics Card Intel Integrated Graphics\r\nMemory System Shared\r\nAudio Stereo speakers with Realtek Audio Controller, 2W x 2 = 4 W\r\nFeatures Wifi, WebCam, Bluetooth, Fingerprint Reader, Backlit Keyboard\r\nExternal Ports USB 3.x, HDMI, RJ45 (LAN), Headphone/Mic combo, USB-C, Card Slot\r\nDimensions Height: 18.06 mm (0.71\") x Width: 361 mm (14.2\") x Depth: 240.9 mm (9.5\")\r\nWeight 3.95 lbs\r\nManufacturer Link Additional Information\r\nWarranty International / Manufacturer\r\nColor Black",
            "discount": "1",
            "disc_value": "15",
            "disc_price": "17925",
            "category": "laptop",
            "sub_category": "notebook",
            "brands": "dell",
            "price": "119500",
            "quantity": "29",
            "image": "https://myshop.pk/pub/media/catalog/product/cache/26f8091d81cea4b38d820a1d1a4f62be/d/e/dell-latitude-3520-myshop-2_2.jpg"
        },
        {
            "name": "Apple Macbook Air - 13\" 256GB",
            "vendor": "1",
            "title": "Apple Macbook Air - 13\" 256GB",
            "slug": "apple-macbook-air---13\"-256gb",
            "description": "More Information\r\nProduct Type Laptop\r\nAvailability\r\nSeries Apple. Macbook Air (2020)\r\nModel MGN63LL-MGND3LL-MGN93LL\r\nOS Version macOS\r\nProcessor Apple\r\nGeneration Latest\r\nSpeed M1 chip, 8 Core CPU, 7 Core GPU\r\nDetail 8-core CPU with 4 perform­ance cores and 4 efficiency cores\r\n7-core GPU\r\n16-core Neural Engine\r\nScreen Size 13.3\"\r\nMax Res 2560 x 1600 :WQXGA\r\nDetail 13.3-inch (diagonal) LED-backlit display with IPS technology; 2560-by-1600 native resolution at 227 pixels per inch with support for millions of colors\r\nRAM 8 GB\r\nDrive 256 GB\r\nType SSD\r\nOptical No Optical Drive\r\nGraphics Card Apple M1 GPU Graphics\r\nMemory System Shared\r\nFeatures Wifi, WebCam, Bluetooth, Backlit Keyboard\r\nExternal Ports Headphone/Mic combo, USB-C",
            "discount": "1",
            "disc_value": "15",
            "disc_price": "31485",
            "category": "laptop",
            "sub_category": "probook",
            "brands": "apple",
            "price": "209900",
            "quantity": "46",
            "image": "https://myshop.pk/pub/media/catalog/product/cache/26f8091d81cea4b38d820a1d1a4f62be/a/p/apple-macbook-air-myshop.pk03_2_1_1.jpg"
        },
        {
            "name": "Apple Macbook Air - 13\" 512GB",
            "vendor": "0",
            "title": "Apple Macbook Air - 13\" 512GB",
            "slug": "apple-macbook-air---13\"-512gb",
            "description": "More Information\r\nProduct Type Laptop\r\nAvailability\r\nSeries Apple. Macbook Air (2020)\r\nModel MGN73LL-MGNE3LL-MGNA3LL\r\nOS Version macOS\r\nProcessor Apple\r\nGeneration Latest\r\nSpeed M1 chip, 8 Core CPU, 8 Core GPU\r\nDetail 8-core CPU with 4 perform­ance cores and 4 efficiency cores\r\n8-core GPU\r\n16-core Neural Engine\r\nScreen Size 13.3\"\r\nMax Res 2560 x 1600 :WQXGA\r\nDetail 13.3-inch (diagonal) LED-backlit display with IPS technology; 2560-by-1600 native resolution at 227 pixels per inch with support for millions of colors\r\nRAM 8 GB\r\nDrive 512 GB\r\nType SSD\r\nOptical No Optical Drive\r\nGraphics Card Apple M1 GPU Graphics\r\nMemory System Shared\r\nFeatures Wifi, WebCam, Bluetooth, Backlit Keyboard\r\nExternal Ports Headphone/Mic combo, USB-C",
            "discount": "1",
            "disc_value": "15",
            "disc_price": "38235",
            "category": "laptop",
            "sub_category": "probook",
            "brands": "apple",
            "price": "254900",
            "quantity": "66",
            "image": "https://myshop.pk/pub/media/catalog/product/cache/26f8091d81cea4b38d820a1d1a4f62be/a/p/apple-macbook-air-myshop.pk03_2_1_2.jpg"
        },
        {
            "name": "Apple Macbook Air - 13\" 16GB 256GB",
            "vendor": "2",
            "title": "Apple Macbook Air - 13\" 16GB 256GB",
            "slug": "apple-macbook-air---13\"-16gb-256gb",
            "description": "More Information\r\nProduct Type Laptop\r\nAvailability\r\nSeries Apple. Macbook Air (2020)\r\nOS Version macOS\r\nProcessor Apple\r\nGeneration Latest\r\nSpeed M1 chip, 8 Core CPU, 7 Core GPU\r\nDetail 8-core CPU with 4 perform­ance cores and 4 efficiency cores\r\n7-core GPU\r\n16-core Neural Engine\r\nScreen Size 13.3\"\r\nMax Res 2560 x 1600 :WQXGA\r\nDetail 13.3-inch (diagonal) LED-backlit display with IPS technology; 2560-by-1600 native resolution at 227 pixels per inch with support for millions of colors\r\nRAM 16 GB\r\nDrive 256 GB\r\nType SSD\r\nOptical No Optical Drive\r\nGraphics Card Apple M1 GPU Graphics\r\nMemory System Shared\r\nFeatures Wifi, WebCam, Bluetooth, Backlit Keyboard\r\nExternal Ports Headphone/Mic combo, USB-C",
            "discount": "0",
            "disc_value": "0",
            "disc_price": "0",
            "category": "laptop",
            "sub_category": "probook",
            "brands": "apple",
            "price": "267900",
            "quantity": "58",
            "image": "https://myshop.pk/pub/media/catalog/product/cache/26f8091d81cea4b38d820a1d1a4f62be/a/p/apple-macbook-air-myshop.pk04_6_1.jpg"
        },
        {
            "name": "Samsung 32 Inch 32N5000 LED TV Price",
            "vendor": "2",
            "title": "Samsung 32 Inch 32N5000 LED TV Price",
            "slug": "samsung-32-inch-32n5000-led-tv-price",
            "description": "The Lowest price of Samsung 32 Inch 32N5000 LED TV in Pakistan is Rs. 35,489, and the estimated average price is Rs. 45,707. 32N5000 is one of the flat, non-smart LED TVs from Samsung having a screen size of 32 inches. It comes equipped with Full HD resolution, HDMI, and USB connectivity. Full HD resolution provides crisp and clear images Wide Color Enhancer improves the image quality and displays bright and rich colors with more detail. You can plug and play your favorite entertainment on this LED TV. Enjoy videos, music, and view photos through a USB connection. Moreover, Clean View in 32N5000 LED TV reduces noise and interference and lets you enjoy everything with refined quality.Previously the price was Rs. 33,749 in November, approximately a 4% increase. Latest May 2022 price from tracked on major eCommerce stores all across Pakistan.",
            "discount": "1",
            "disc_value": "15",
            "disc_price": "5323.35",
            "category": "tv",
            "sub_category": "led",
            "brands": "samsung",
            "price": "35489",
            "quantity": "33",
            "image": "https://pakistanistores.com/public/data/images/6ef3f6f956ef81cdc9dc19ebc664f225.jpg"
        },
        {
            "name": "Sony 40 Inch 40W652D LED TV Price",
            "vendor": "2",
            "title": "Sony 40 Inch 40W652D LED TV Price",
            "slug": "sony-40-inch-40w652d-led-tv-price",
            "description": "Screen Size: 40-inch Resolution: 1920 x 1080 (FHD) Smart Features: No Hdmi: Yes\r\nThe Sony 40W652D is a higher midrange LED TV that has advanced features such as X-Protection Pro, X-Reality Pro, and Live Color technology Even though it is not a smart TV, the excellent connectivity options that support USB, HDMI, and smartphone connectivity ensure that you can stream your favorite movies and TV shows on the LED TV. The Dolby Digital audio system ensures that you have a clear, natural audio playback when watching TV. The picture quality is superb and the Live Color technology ensures that the Sony 40W652D delivers vibrant colors and excellent contrast.",
            "discount": "0",
            "disc_value": "0",
            "disc_price": "0",
            "category": "tv",
            "sub_category": "led",
            "brands": "sony",
            "price": "65999",
            "quantity": "89",
            "image": "https://pakistanistores.com/public/data/images/15492040076ebde75379376f4f506069279981f224.jpg"
        },
        {
            "name": "Sony 43 Inch 43W660F LED TV Price",
            "vendor": "0",
            "title": "Sony 43 Inch 43W660F LED TV Price",
            "slug": "sony-43-inch-43w660f-led-tv-price",
            "description": "Screen Size: 43-inch Resolution: 1920 x 1080 (FHD) Smart Features: No Hdmi: Yes\r\nThe Sony 43W660F is one of the newest models from the Sony Bravia series that provides a comfortable viewing experience with a durable design. This 43-inch flat FHD LED TV features the X-Reality Pro engine with Live Colour technology that ensures excellent color reproduction with great contrast and sharpness. Overall, the image quality is quite impressive, particularly if you are looking to watch 1080p TV shows and movies on your LED TV. The connectivity features cover all the basics including USB, HDMI, and smartphone connectivity. The HDR10 feature further adds to the overall quality of the picture enabling a superb viewing for users. Overall, if you are looking for an excellent non-smart FHD LED TV then the Sony 43W660F is a good choice to consider.",
            "discount": "0",
            "disc_value": "0",
            "disc_price": "0",
            "category": "tv",
            "sub_category": "led",
            "brands": "sony",
            "price": "74999",
            "quantity": "13",
            "image": "https://pakistanistores.com/public/data/images/15492040664ee8d767352857b2f694129f23065c24.jpg"
        },
        {
            "name": "TCL 32 Inch Led Tv D310 Price",
            "vendor": "1",
            "title": "TCL 32 Inch Led Tv D310 Price",
            "slug": "tcl-32-inch-led-tv-d310-price",
            "description": "Screen Size: 32-inch Resolution: 1366 x 768 (HD) Smart Features: No Hdmi: Yes\r\nD310 is a basic, non-smart, entry-level LED TV from TCL which comes with features of HD resolution, 32 inches display, and USB & HDMI connections. Natural Light Engine in this LED TV provides the brightest and highest contrast level to ensure true color reproduction. Turbo Sound enhances your entertainment experience and the USB & HDMI connections allow you to share your favorite data from different technologies and systems and display on your TV. Although it is not a smart TV, it is a good choice for the people who are on a budget.",
            "discount": "0",
            "disc_value": "0",
            "disc_price": "0",
            "category": "tv",
            "sub_category": "led",
            "brands": "tcl",
            "price": "27999",
            "quantity": "80",
            "image": "https://pakistanistores.com/public/data/images/4538c03ac4db9673b7c4b066dec4aa13.jpg"
        },
        {
            "name": "PEL 32\" Smart HD LED TV",
            "vendor": "0",
            "title": "PEL 32\" Smart HD LED TV",
            "slug": "pel-32\"-smart-hd-led-tv",
            "description": "Screen Size: 32-inch Resolution: 1366 x 768 (HD) Smart Features: Yes HDMI: Yes\r\nPEL ColorOn 32\" is a Smart LED TV with HD resolution. It is a budget and pretty basic LED but of good quality. It's smart features lets you watch YouTube and Netflix in HD quality and has the HDMI connectivity to connect your devices to play anything on a bigger display.",
            "discount": "0",
            "disc_value": "0",
            "disc_price": "0",
            "category": "tv",
            "sub_category": "smart",
            "brands": "pel",
            "price": "35900",
            "quantity": "38",
            "image": "https://pakistanistores.com/public/data/images/355aa5dbbac28fda218a441c3105521d.jpg"
        },
        {
            "name": "Huawei Nova 9",
            "vendor": "0",
            "title": "Huawei Nova 9",
            "slug": "huawei-nova-9",
            "description": "Huawei Nova 9 price in Pakistan\r\nHuawei Nova 9 price in Pakistan is Rs. 107,999. Official dealers and warranty providers regulate the retail price of Huawei mobile products in official warranty.\r\n\r\nPrice of Huawei Nova 9 in Pakistan is Rs. 107,999.\r\nPrice of Huawei in USD is $537.\r\nHuawei Nova 9 - Flagship Smartphone With Kirin Chipset\r\nHuawei is unveiling its new Nova 9 to the market soon. Huawei is working on its new device of its Nova-series. The smartphone will be launch in August of October this year. The Chinese company is launching a flagship smartphone and it will be called Huawei Nova 9. The smartphone got a Chipset of Qualcomm SM7325 Snapdragon 778G 4G SoC which is the most powerful chipset in the market now a day's and to give more power to this Huawei's Nova 9 to have a 2.4 GHz Octa-Core processor inside the phone to make the device ultra fast. And also there is a GPU of Adreno 642L under the hood of this smartphone. The display screen size of the smartphone is 6.57 Inches and It will provide the user with full HD plus the resolution of 1080 x 2340 Pixels. The new Huawei Nova 9's having an OLED Capacitive Touchscreen display that is the latest one and well known for its outstanding results. The smartphone is using Corning Gorilla Glass for protection purposes. This handset Nova 9 by Huawei will be paired with a gigantic RAM capacity of 8 gigabytes. The chipset and the RAM capacity of the device show that it will enable the user to execute things with this smartphone within seconds. The internal storage capacity of the smartphone is 256 gigabytes that is enough to store a huge amount of data for future use. On the rear of the Huawei 9, there is a Quad Camera setup. The main sensor will be 50 megapixels, 8 megapixels ultra-wide, 2 megapixels depth, 2 megapixels macro sensors. The selfie shooter of the phone is 32 megapixels wide, to make taking selfies more easy and attractive. The Huawei Nova's 9 is having an under-display, optical fingerprint reader to secure the data on the smartphone and only allow the authorized person. The Huawei Nova 9 will be fueled with a Non-removable Li-Po 4500 mAh battery that will carry support for Fast charging. Samsung and other tech giants will face serious competition when the coming smartphone Nova 9's will release.",
            "discount": "1",
            "disc_value": "15",
            "disc_price": "16199.85",
            "category": "mobile",
            "sub_category": "android",
            "brands": "huawei",
            "price": "107999",
            "quantity": "11",
            "image": "hhttps://www.whatmobile.com.pk/admin/images/Huawei/HuaweiNova9-b.jpg"
        },
        {
            "name": "Infinix Zero 5G",
            "vendor": "2",
            "title": "Infinix Zero 5G",
            "slug": "infinix-zero-5g",
            "description": "Infinix Zero 5G price in Pakistan\r\nInfinix Zero 5G price in Pakistan is Rs. 49,999. Official dealers and warranty providers regulate the retail price of Infinix mobile products in official warranty.\r\n\r\nPrice of Infinix Zero 5G in Pakistan is Rs. 49,999.\r\nPrice of Infinix in USD is $248.\r\nInfinix Zero 5G - A Dimensity Smartphone\r\nInfinix is launching a new smartphone Zero 5G to the market soon. Infinix is working on a new device with 5G technology. The coming smartphone of the company was popped in the database of the Play Console. The smartphone will be a mid-ranger and will be named Infinix Zero 5G. The smartphone got a Chipset of Dimensity 900 which is the most powerful chipset in the market now a day's, and to give more power to this Infinix's Zero 5G to have an Octa-Core processor inside the phone to make the device ultra fast. And also there is a GPU of Mali G68 under the hood of this smartphone. The display screen size of the smartphone is 6.78 Inches and It will provide the user with full HD plus the resolution of 1080 x 2460 Pixels. The new Infinix Zero 5G's has a IS LCD Capacitive Touchscreen display that is the latest one and well known for its outstanding results. The smartphone is using Corning Gorilla Glass for protection purposes. The coming handset Zero 5G by Infinix will be paired with a gigantic RAM capacity of 8 gigabytes. The chipset and the RAM capacity of the device show that it will enable the user to execute things with this smartphone within seconds. The internal storage capacity of the smartphone is 128 gigabytes that is enough to store a huge amount of data for future use. On the rear of the Infinix 5G, there is a triple camera setup. The main sensor will be 48 megapixels, 13 megapixels, 2 megapixels. The selfie shooter of the phone is 16 megapixels wide, to make taking selfies more easy and attractive. The Infinix Zero's 5G is having a side-mounted fingerprint reader to secure the data on the smartphone and only allow the authorized person. The Infinix Zero 5G will be fueled with a Non-removable Li-Po 5000 mAh battery that will carry support for Fast charging of 33W. Infinix Zero 5G and other tech giants will face serious competition when the coming smartphone Zero 5G's will released.",
            "discount": "0",
            "disc_value": "0",
            "disc_price": "0",
            "category": "mobile",
            "sub_category": "android",
            "brands": "infinix",
            "price": "49999",
            "quantity": "23",
            "image": "https://www.whatmobile.com.pk/admin/images/Infinix/InfinixZero5G-b.jpg"
        },
        {
            "name": "itel Vision 3",
            "vendor": "0",
            "title": "itel Vision 3",
            "slug": "itel-vision-3",
            "description": "itel Vision 3 price in Pakistan\r\nitel Vision 3 price in Pakistan is Rs. 16,299. Official dealers and warranty providers regulate the retail price of itel mobile products in official warranty.\r\n\r\nPrice of itel Vision 3 in Pakistan is Rs. 16,299.\r\nPrice of itel in USD is $81.\r\nitel Vision 3 - Anther Budget-Friendly Smartphone\r\nitel is launching a new Vision 3 to the market. The Chinses company is unveiling a new smartphone of its Vision series. The coming smartphone will be a budget-friendly phone and will be named itel Vision 3. The smartphone got a Chipset of Unisoc SC9863A, which is the most powerful chipset, and to give more power to this handset has a 1.6 GHz Octa-Core processor inside the itel's Vision 3 to make the device ultra fast. And also there is a GPU of PowerVR GE8322 under the hood of this smartphone. The display screen size of the smartphone is 6.6 Inches and It will provide the user with full HD plus the resolution of 720 x 1600 Pixels. The new itel Vision 3's having an IPS LCD Capacitive Touchscreen display that is the latest one and well known for its outstanding results. The upcoming new handset of the Vision 3 by itel will be paired with a gigantic RAM capacity of 3 gigabytes. The chipset and the RAM capacity of the device show that it will enable the user to execute things with this smartphone within seconds. The internal storage capacity of the itel 2GB is 32 gigabytes which is enough to store a huge amount of data for future use. On the rear of the smartphone, there is a Dual Camera setup. The main sensor of the itel Vision's 3 will be 8 megapixels, AI Lens. The selfie shooter of the phone is 5 megapixels to make taking selfies more easy and more attractive. The itel Vision 3 is having a rear-mounted fingerprint reader to secure the data on the smartphone and only allows the authorized person. The device will be fueled with a Non-removable Li-Po 5,000 mAh battery that will carry support for Fast charging of 18W. Samsung and other tech giants will face serious competition when the coming Vision 3's will be released.",
            "discount": "0",
            "disc_value": "0",
            "disc_price": "0",
            "category": "mobile",
            "sub_category": "android",
            "brands": "itel",
            "price": "18499",
            "quantity": "76",
            "image": "https://www.whatmobile.com.pk/admin/images/itel/itelVision33GB-b.jpg"
        },
        {
            "name": "Oppo F21",
            "vendor": "0",
            "title": "Oppo F21",
            "slug": "oppo-f21",
            "description": "Oppo F21 price in Pakistan\r\nOppo F21 price in Pakistan is expected to be Rs. 48,999. Oppo F21 Expected to be launched on Apr 30, 2022. This is 6 GB RAM / 128 GB internal storage variant of Oppo which is available in Various colours.\r\n\r\nExpected Price of Oppo F21 in Pakistan is Rs. 48,999.\r\nExpected Price of Oppo in USD is $365.\r\nOppo F21 - A Powerful Smartphone\r\nThe Chinese Oppo is launching the F21 smartphone to the market. This company may be preparing to launch the F17 successor in India next month. While one group of tipsters believe the smartphone will be called F19, others are suggesting the company might end up calling it the Oppo F21. The smartphone will be powered by one of the latest chipsets available for smartphones in the market that is called Mediatek Helio. The new Oppo's F21 has got a 2.2 GHz Octa-Core processor under the hood of this handset. This new upcoming smartphone has a 6.5 Inches screen size which is a big-screen display, with a Super AMOLED Capacitive Touchscreen, and this device Oppo F21's going to have a full-HD display with a resolution of 1080 x 2400 Pixels. And talking about the Protection of this smartphone it has Corning Gorilla Glass 3+. The upcoming new Oppo sharp F21 is going to packing the upcoming smartphone with 6 gigabytes RAM, which is the highest point of RAM used in this smartphone so you can say that your phone is going to run at a super-fast speed because of its powerful RAM. Oppo has got 128 gigabytes of storage in F21 which means that the capacity of your data is unlimited. On the rear of the smartphone, there is a Quad Camera setup. The main sensor of the smartphone F21 will be 48 megapixels. 8 megapixels, 2 megapixels, 2 megapixels. The selfie shooter in this phone will be 16 megapixels to make taking selfies more easy and attractive with this new F21. The under-display, optical sensor will allow the F21 to protect its data by only allowing the authorized person. The F21 by Oppo will be fueled with a Non-removable Li-Po 4300 mAh battery that will carry support for Fast charging. Samsung and other tech giants will face serious competition when this Oppo F21 will release.",
            "discount": "1",
            "disc_value": "15",
            "disc_price": "7949.85",
            "category": "mobile",
            "sub_category": "android",
            "brands": "oppo",
            "price": "52999",
            "quantity": "23",
            "image": "https://www.whatmobile.com.pk/admin/images/Oppo/OppoF20Pro-b.jpg"
        },
        {
            "name": "Realme 9 pro",
            "vendor": "2",
            "title": "Realme 9 pro",
            "slug": "realme-9-pro",
            "description": "Realme 9 pro price in Pakistan\r\nRealme 9 pro price in Pakistan is expected to be Rs. 49,999. Realme 9 pro Expected to be launched on Mar 15, 2022. This is 6 GB RAM / 128 GB internal storage variant of Realme which is available in Midnight Black, Aurora Green, Sunrise Blue colours.\r\n\r\nExpected Price of Realme 9 pro in Pakistan is Rs. 49,999.\r\nExpected Price of Realme in USD is $373.\r\nRealme 9 pro - A Pro Variant Of Realme\r\nRealme is unveiling its new 9 Pro to the market. The Realme is launching its new handsets of its 9-series of smartphones. This is one of them, the device is in a mid-range segment. The company is adding a new Pro variant and it will be called Realme 9 pro. The upcoming smartphone of the company has got a chipset of Qualcomm SM6375 Snapdragon 695, which is used in mid-range devices, to give more power to the handset there is a 2.2 Ghz Octa-Core processor under the hood of this Realme's 9 Pro. Also, there is a GPU of Adreno 619 in this smartphone. This new upcoming smartphone has a 6.6 Inches screen size which is a big-screen display. The new Realme 9 pro's going to have a IPS LCD Capacitive Touchscreen, and this device has got a full-HD display with a resolution of 1080 x 2400 Pixels. The upcoming new 9 pro by Realme has got 8 gigabytes of RAM, which is a powerful RAM used in this smartphone so you can say that your phone is going to run at a super-fast speed because of its powerful RAM. The built-in storage capacity of the Realme pro is 128 gigabytes which means that the capacity of your data is unlimited. On the rear of the smartphone, there is a Quad Camera setup. The main sensor of the phone will be 64 megapixels main sensor 8 megapixels' ultra-wide, and the 2 megapixels depth sensor. The selfie shooter in this Realme 9's pro will be a single camera which is, 16 megapixels to make taking selfies more easy and attractive. The device has got an under-display, the optical fingerprint reader is there to protect it from any unauthorized person. The battery of the Realme 9 Pro is also a massive one. The handset is fueled with (Li-Po Non-removable), 5,000 mAh battery to get enough backup time and the smartphone got a Fast charging. Now Samsung and other smartphone companies will have a competitor when the 9 pro's launched.",
            "discount": "0",
            "disc_value": "0",
            "disc_price": "0",
            "category": "mobile",
            "sub_category": "android",
            "brands": "realme",
            "price": "69999",
            "quantity": "77",
            "image": "https://www.whatmobile.com.pk/admin/images/Realme/Realme9proPlus-b.jpg"
        },
        {
            "name": "Samsung Galaxy S22",
            "vendor": "1",
            "title": "Samsung Galaxy S22",
            "slug": "samsung-galaxy-s22",
            "description": "Samsung Galaxy S22 price in Pakistan Samsung Galaxy S22 price in Pakistan is Rs. 179,999. Official dealers and warranty providers regulate the retail price of Samsung mobile products in official warranty. Price of Samsung Galaxy S22 in Pakistan is Rs. 179,999. Price of Samsung in USD is $894. Samsung Galaxy S22 - The Company's Beast Phone Samsung is working on a Galaxy S22 smartphone. This smartphone manufacturer company is working on a beast because it is more than a flagship device. The upcoming smartphone from Samsung will be a powerful handset of the year. The company will call it the Samsung Galaxy S22. The smartphone will be empowered by the Qualcomm SM8450 Snapdragon 8 Gen 1 (4 nm) chipset, this chipset is used in flagship phones. To give more power to this handset there is a 3.0 GHz Octa-Core inside this Samsung's Galaxy S22. There is also a GPU of Adreno 730 under the hood of this smartphone. The device has got a Dynamic AMOLED 2X Capacitive Touchscreen display with a screen size of 6.1 inches and has a full HD+ of resolution 1080 x 2400 Pixels. Samsung Galaxy S22's going to have a bigger screen size, the users of this device will be enjoying using it. They have a Dynamic AMOLED 2X Capacitive Touchscreen, with a full HD resolution of 1080 x 2400 Pixels under the hood of the Galaxy S22 by Samsung. The Protection of the screen this device has got Corning Gorilla Glass Victus. The RAM that is coupled with the SoC is 8 gigabytes. This is the high-end RAM capacity that is used in the Samsung S22. Both, the chipset and the RAM will enhance the processing speed of the handset a great deal. The internal storage is 256 gigabytes that is enough to store the data on the Samsung Galaxy's S22 for the rest of your life. There is a Triple Camera setup in the back of this handset, The main sensor will be 50 megapixels, and the others are yet to be confirmed. The selfie shooter of the Samsung Galaxy S22 is a single camera, which will change your lifestyle. The under-display, ultrasonic fingerprint reader of the handset is there to protect it from any unauthorized person. And the device is IP68 dust/water resistant (up to 1.5m for 30 mins). The battery of the new Galaxy S22's will be somewhere around 3700 mAh. This is enough power for this smartphone, and there is a Fast battery charging.",
            "discount": "0",
            "disc_value": "0",
            "disc_price": "0",
            "category": "mobile",
            "sub_category": "android",
            "brands": "samsung",
            "price": "179999",
            "quantity": "19",
            "image": "https://www.whatmobile.com.pk/admin/images/Samsung/SamsungGalaxyS22-b.jpg"
        },
        {
            "name": "Tecno Spark 8C",
            "vendor": "1",
            "title": "Tecno Spark 8C",
            "slug": "tecno-spark-8c",
            "description": "Tecno Spark 8C price in Pakistan\r\nTecno Spark 8C price in Pakistan is Rs. 17,999. Official dealers and warranty providers regulate the retail price of Tecno mobile products in official warranty.\r\n\r\nPrice of Tecno Spark 8C in Pakistan is Rs. 17,999.\r\nPrice of Tecno in USD is $89.\r\nTecno Spark 8C - A Big Battery Phone\r\nTecno is unveiling its all new Spark 8C to the market soon. The Chinese smartphone company Tecno has released a new handset in its Spark-series. The coming device of the company will be a budget-friendly phone. The newcomer will be called Tecno Spark 8C. The new smartphone will be empowered by the powerful chipset called Unisoc T606. This chipset is used in mid-range smartphones, and to give more power to this Tecno's Spark 8C it has a Quad-Core processor inside the handset. The device has got an IPS LCD Capacitive Touchscreen and also there is a GPU of ARM Mali-G57. The upcoming new Tecno Spark 8C's going to have a big screen size of 6.6 Inches, the users will enjoying using this screen size. This smartphone has a full HD plus resolution of 720 x 1612 Pixels. The Spark 8C by Tecno has 2 gigabytes of RAM that will assist the chipset to perform well and make the execution speed lightning fast. In this upcoming handset, there are 64 gigabytes of internal storage capacity in Tecno 8C. which is enough to store a huge amount of data for a long period of time that can be used in the future. But you can also increase the capacity of storage of the device as it carries support for the MicroSD card. The Tecno Spark's 8C will come equipped with a dual rear camera setup. The main sensor of the handset will be 13 megapixels and the secondary sensor will be an AI sensor. The selfie shooter of the phone will be 8 megapixels. The Tecno Spark 8C features a rear-mounted fingerprint reader plus Face Unlock, that will detect the unauthorized user and will stop him from getting into the phone and steal data. The handset is fueled with a gigantic battery that is going to be a Non-removable Li-Po 5,000 mAh battery Also there is a Battery charging of 10W. The coming Spark 8C's will be a good rival for the Samsung upcoming smartphones.",
            "discount": "0",
            "disc_value": "0",
            "disc_price": "0",
            "category": "mobile",
            "sub_category": "android",
            "brands": "tecno",
            "price": "22999",
            "quantity": "38",
            "image": "https://www.whatmobile.com.pk/admin/images/Tecno/TecnoSpark8C4GB-b.jpg"
        },
        {
            "name": "Vivo X80",
            "vendor": "1",
            "title": "Vivo X80",
            "slug": "vivo-x80",
            "description": "Vivo X80 price in Pakistan\r\nVivo X80 price in Pakistan is Rs. 159,999. Official dealers and warranty providers regulate the retail price of Vivo mobile products in official warranty.\r\n\r\nPrice of Vivo X80 in Pakistan is Rs. 159,999.\r\nPrice of Vivo in USD is $795.\r\nVivo X80 - A Powerful Mid-Ranger\r\nSmart tech Vivo is unveiling X80 to the market soon. The Chinese manufacturer is working on a successor of the Vivo X70 series, which was launched a few months ago. Now the company is launching a new series of phones and that will be called Vivo X80. The smartphone will be powered by one of the latest chipsets available for smartphones in the market that is called MediaTek Dimensity 9000. Also, there is a powerful GPU of ARM Mali-G710. The new Vivo's X80 has got an Octa-Core processor under the hood of this handset. This new upcoming smartphone has a 6.78 Inches screen size which is a big-screen display, with a Capacitive LTPO AMOLED Capacitive Touchscreen, and this device Vivo X80's going to have a full-HD display with a resolution of 1080 x 2400 Pixels. Also, there is the latest operating system called Android 12. The upcoming new Vivo sharp X80 is going to pack the upcoming smartphone with 12 gigabytes RAM, which is the highest point of RAM used in this smartphone so you can say that your phone is going to run at a super-fast speed because of its powerful RAM. Vivo has got 256 gigabytes of storage in X80 which means that the capacity of your data is unlimited. On the rear of the smartphone, there is a Triple Camera setup. The main sensor of the smartphone X80 will be 50 megapixels, 12 megapixels, 12 megapixels. The selfie shooter in this phone will be 32 megapixels to make taking selfies more easy and attractive with this new X80. The under-display, optical sensor will allow the X80 to protect its data by only allowing the authorized person. The X80 by Vivo will be fueled with a Non-removable Li-Po 4500 mAh battery that will carry support for Fast charging of 55W. Samsung and other tech giants will face serious competition when this Vivo X80 will release.",
            "discount": "1",
            "disc_value": "15",
            "disc_price": "23999.85",
            "category": "mobile",
            "sub_category": "android",
            "brands": "vivo",
            "price": "159999",
            "quantity": "79",
            "image": "https://www.whatmobile.com.pk/admin/images/Vivo/VivoX80-b.jpg"
        },
        {
            "name": "Xiaomi 12",
            "vendor": "2",
            "title": "Xiaomi 12",
            "slug": "xiaomi-12",
            "description": "Xiaomi 12 price in Pakistan Xiaomi 12 price in Pakistan is Rs. 179,999. Official dealers and warranty providers regulate the retail price of Xiaomi mobile products in official warranty. Price of Xiaomi 12 in Pakistan is Rs. 179,999. Price of Xiaomi in USD is $894. Xiaomi 12- A Most Powerful Machine In The Planet Smart tech Xiaomi will unveil 12 series of smartphones to the market soon this year. According to reports, the company is readying itself to produce its next-level flagship smartphone. Xiaomi will launch two variants in its new 12-series, the first one will be called Xiaomi 12. The smartphone will be powered by one of the latest chipsets in the market Qualcomm Snapdragon 8 Gen 1. The Chipset of the smartphone is also a flagship chipset that can all the high-end specs with accuracy and ease. The new Xiaomi's 12 has a 3.0 GHz Octa-Core processor to give more power to this chipset. The device has a 6.28 Inches massive screen size, the users of this device will be enjoying using it. The Xiaomi 12's going with an AMOLED Capacitive Touchscreen, with a full HD resolution of 1080 x 2340 Pixels under the hood of the handset. The Protection of the screen this device has got Corning Gorilla Glass Victus, also there is a powerful GPU of Adreno. The SoC of the Xiaomi sharp 12 is paired with 8 gigabytes of RAM. The chipset and the RAM of the device will make the processing speed of the phone lightning fast. The upcoming new Xiaomi has got 128 GB of internal storage in 12. This is enough storage capacity that will give you enough space to place a huge amount of data for future use. There is a Triple Camera setup in the back of this handset, The main sensor will be 50 megapixels, and the other will be confirmed yet. The 12 selfie shooter has a single selfie camera, and that is 32 megapixels which will change your lifestyle. The upcoming new 12 has got the latest operating system Android 12. There is an under-display, optical fingerprint reader that is there to protect it from any unauthorized person. The battery of the 12 is also a massive one. The handset is fueled with (Li-Po Non-removable), 4500 mAh battery to get enough backup time and the 12 by Xiaomi got a Fast charging of 67W, it can charge the device very quickly. Now Samsung and other smartphone companies will be looking to bring features like Xiaomi 12.",
            "discount": "0",
            "disc_value": "0",
            "disc_price": "0",
            "category": "mobile",
            "sub_category": "android",
            "brands": "xiaomi",
            "price": "179999",
            "quantity": "6",
            "image": "https://www.whatmobile.com.pk/admin/images/Xiaomi/Xiaomi12-b.jpg"
        },
        {
            "name": "Keeway SUPERLIGHT 200",
            "vendor": "0",
            "title": "Keeway SUPERLIGHT 200",
            "slug": "keeway-superlight-200",
            "description": "Factory customs are some of the most popular bikes on earth, and Keeway’s Superlight 200 fits the bill perfectly.\r\nCategory Naked Bike\r\nDisplacement 200cc\r\nEngine Type 4-Stroke Single Cylinder Air Cooled\r\nStarter Electric\r\nFront Brakes Single Disc\r\nRear Brakes Drum Brake\r\nDesigned to evoke the look, sound and feel of classic customs, the Superlight 200 features the fat-fender, thick-tire, custom-painted and chrome-tinged look that style-conscious riders love.",
            "discount": "1",
            "disc_value": "15",
            "disc_price": "97500",
            "category": "bike",
            "sub_category": "sports",
            "brands": "keeway",
            "price": "650000",
            "quantity": "8",
            "image": "https://motorcycleshop.pk/779-large_default/keeway-superlight-200-price-in-pakistan-rating-reviews-and-pictures.jpg"
        },
        {
            "name": "Keeway K-Light 202",
            "vendor": "2",
            "title": "Keeway K-Light 202",
            "slug": "keeway-k-light-202",
            "description": "Everything you need for a great ride, and nothing more. Handlebar. Mirrors. Speedo. Controls.Its Four-Stroke Single-Cylinder engine is Liquid-cooled for durability and offers a perfect blend of smooth power. There’s also electronic ignition and kick starting, both front and rear disc brakes, a unique exhaust, and a multi-mode Digital instrument, performance and affordability.\r\nCategory Naked Bike\r\nDisplacement 200cc\r\nEngine Type 4-Stroke Single Cylinder Air Cooled\r\nStarter Electric\r\nFront Brakes Single Disc\r\nRear Brakes Drum Brake",
            "discount": "0",
            "disc_value": "0",
            "disc_price": "0",
            "category": "bike",
            "sub_category": "sports",
            "brands": "keeway",
            "price": "675000",
            "quantity": "51",
            "image": "https://motorcycleshop.pk/783-large_default/keeway-k-light-202-price-in-pakistan-rating-reviews-and-pictures.jpg"
        },
        {
            "name": "Yamaha YBR 125",
            "vendor": "0",
            "title": "Yamaha YBR 125",
            "slug": "yamaha-ybr-125",
            "description": "The Yamaha YBR 125 is a light motorcycle made by Yamaha that succeeds it's previous model for this segment, the Yamaha SR125. Introduced in 2005, it comes in naked, faired and 'custom' variants. It has a single-cylinder, air-cooled, four-stroke engine, displacing 124 cc. Key features of the motorcycle includes; Engine: OHC 125 CC\r\nDesign: Sporty\r\nTransmission: 5 Speed\r\nHead Light: HS1 35W/35W",
            "discount": "1",
            "disc_value": "15",
            "disc_price": "34800",
            "category": "bike",
            "sub_category": "sports",
            "brands": "yamaha",
            "price": "232000",
            "quantity": "7",
            "image": "https://motorcycleshop.pk/27-large_default/yamaha-ybr-125-price-in-pakistan-rating-reviews-and-pictures.jpg"
        },
        {
            "name": "Yamaha YBR 125G",
            "vendor": "2",
            "title": "Yamaha YBR 125G",
            "slug": "yamaha-ybr-125g",
            "description": "The Yamaha YBR 125G 4-Stroke motorcycle designed specially for convenience and adventure with 5-speed transmission, engine guard, long front shock absorbed with stylish double front fender and many other appealing features. Colors:\r\n\r\nYBR 125G RED\r\nYBR 125G BLUE\r\nYBR 125G BLACK\r\nPERFORMANCE, DESIGN & COMFORT\r\n\r\nWITH ITS SPLENDID AND UNRUFFLED PERFORMANCE, DESIGN and COMFORT, YBR 125G WON'T LET YOU DOWN.",
            "discount": "1",
            "disc_value": "15",
            "disc_price": "36750",
            "category": "bike",
            "sub_category": "sports",
            "brands": "yamaha",
            "price": "245000",
            "quantity": "13",
            "image": "https://motorcycleshop.pk/826-large_default/yamaha-ybr-125g-price-in-pakistan-rating-reviews-and-pictures.jpg"
        },
        {
            "name": "United US 100CC Scooty",
            "vendor": "2",
            "title": "United US 100CC Scooty",
            "slug": "united-us-100cc-scooty",
            "description": "Category\r\nStreet Bike\r\nDisplacement\r\n100 cc\r\nEngine Type\r\n4 stroke single cylinder\r\nCompression Ratio\r\n8.8:1\r\nFuel Control\r\nInjuction\r\nTransmission\r\nChain\r\nStarter\r\nKick Start\r\nFront Tyre\r\n2.50 -18\r\nRear Tyre\r\n2.50 -18\r\nDry Weight\r\n90 kg\r\nFuel Tank Capacity\r\n5.5 Liters",
            "discount": "1",
            "disc_value": "15",
            "disc_price": "23250",
            "category": "bike",
            "sub_category": "general",
            "brands": "united",
            "price": "155000",
            "quantity": "67",
            "image": "https://motorcycleshop.pk/989-large_default/united-us-100cc-scooty.jpg"
        },
        {
            "name": "United US125 Euro II",
            "vendor": "1",
            "title": "United US125 Euro II",
            "slug": "united-us125-euro-ii",
            "description": "United US 125 Euro II presents in that stage when there is a extraordinary demand for fuel well-organized bikes. The main objective to present the United US 125 is to object potential customers who have high desires for fuel efficient transportation. United US 125 incorporates a manifest Euro II technology completely engineered to succeed your range requirements. Not only this, a noticeably low price label of United US 125 Euro II provides a chance to the customers to consider this bike over other 125cc bikes in the market. United US 125 Euro II is a perfect mixture of engineered fuel competent technology and commanding 125cc engine.",
            "discount": "1",
            "disc_value": "15",
            "disc_price": "13800",
            "category": "bike",
            "sub_category": "general",
            "brands": "united",
            "price": "92000",
            "quantity": "5",
            "image": "https://motorcycleshop.pk/463-large_default/united-us125-euro-ii-price-in-pakistan-rating-reviews-and-pictures.jpg"
        },
        {
            "name": "Honda Civic RS",
            "vendor": "2",
            "title": "Honda Civic RS",
            "slug": "honda-civic-rs",
            "description": "MILEAGE (KM/LITER)\r\n11 to 14\r\nTransmission\r\nAutomatic (CVT)\r\nFuel Type\r\nPetrol\r\nEngine\r\n1500 cc\r\nHonda Civic RS Price in Pakistan\r\nThe price of Honda Civic RS in Pakistan is PKR 6,649,000. This price of Civic RS is ex-factory and does not include freight, taxes and other documentation charges.\r\n\r\nVariant Ex-Factory Price On Road Price\r\nHonda Civic RS\r\nPKR 6,649,000\r\nGet Civic RS On Road Price\r\nHonda Civic RS Colors\r\nHonda Civic RS is available in 7 different colours - Carnelian Red Pearl, Crystal Black Pearl, Lunar Silver Metallic, Meteoroid Gray Metalic, Morning Mist Blue Metallic, Taffeta White , and Urban Titanium Metallic\r\n\r\nCarnelian Red Pearl\r\n\r\nCrystal Black Pearl\r\n\r\nLunar Silver Metallic\r\n\r\nMeteoroid Gray Metalic\r\n\r\nMorning Mist Blue Metallic\r\n\r\nTaffeta White\r\n\r\nUrban Titanium Metallic\r\n\r\nHonda Civic RS Specifications & Features\r\nSpecifications\r\nFeatures\r\nSpecifications\r\nDimensions\r\nOverall Length 4687 mmKerb Weight 1396 KGOverall Width 1802 mmBoot Space 409 LOverall Height 1432 mmSeating Capacity 5 personsWheel Base 2735 mmNo. of Doors 4 doorsGround Clearance 154 mm\r\nEngine/ Motor\r\nEngine Type PetrolNo. of Cylinders 4Displacement 1500 ccCylinder Configuration In LineHorse Power 176 HP @ 6000 RPMCompression Ratio 10.3:1Torque 220 Nm @ 4500 RPMValves per Cylinder 4Fuel System PGM FIValve Mechanism DOHC DUAL VTC+EXH-VTECMax Speed 260 KM/H\r\nTransmission\r\nTransmission Type Automatic (CVT)Gearbox -CVT\r\nSteering\r\nSteering Type Rack and PinionMinimum Turning Radius 5.3mPower Assisted Electric Power Steering\r\nSuspension & Brakes\r\nSuspension Front: Macpherson with Stabilizer Rear: Multilink with StabilizerBrakes Front: Disc Rear: Disc\r\nWheels and Tyres\r\nWheel Type Alloy WheelsTyre Size 215/50/R17Wheel Size 17 inSpare Tyre PCD -Spare Tyre Size 17 in\r\nFuel Economy\r\nMileage City 11 KM/LFuel Tank Capacity 47 LMileage Highway 14 KM/L\r\nFeatures\r\nSafety\r\nNo. of Airbags 2Anti-Lock Braking System (ABS) No. of Seatbelts 5Down Hill Assist Control Immobilizer Hill Start Assist Control Child Lock Traction Control ISOFIX Child Seat Anchors Vehicle Stability Control\r\nExterior\r\nAlloy Wheels Adjustable Headlights Colored Outside Door Handles Piano BlackFog Lights Side Mirrors With Indicators DRLs Rear Spoiler Sun Roof / Moon Roof /\r\nInstrumentation\r\nTachometer Multi Info\r\nInfotainment\r\nCD/DVD Player / Front Speakers USB and Auxillary Cable Rear Speakers Display Size 9.0 inRear Seat Entertainment\r\nComfort and Convenience\r\nAir Conditioner Cruise Control Climate Control Driving Modes Rear AC Vents Key Type Smart EntryHeater Keyless Entry Heated Seats Push Start Defogger Central Locking CoolBox Power Door Locks Navigation Power Steering Optional Navigation Power Windows Front Camera Power Mirrors Rear Camera Power Boot Rear Central Control Cup Holders Rear Folding Seat Arm Rest Rear Headrest 3Handbrake ElectricRear Wiper Interior Lighting Seat Material Type Hi-Grade LeatherFront Power Outlet Steering Adjustment Rear Power Outlet Steering Switches",
            "discount": "1",
            "disc_value": "15",
            "disc_price": "997350",
            "category": "car",
            "sub_category": "manual",
            "brands": "honda",
            "price": "6649000",
            "quantity": "8",
            "image": "https://cache2.pakwheels.com/system/car_generation_pictures/6345/original/Honda_Civic_Front_Right_Angled.jpg?1647970561"
        },
        {
            "name": "Toyota Corolla Altis X Manual 1.6",
            "vendor": "0",
            "title": "Toyota Corolla Altis X Manual 1.6",
            "slug": "toyota-corolla-altis-x-manual-1.6",
            "description": "MILEAGE (KM/LITER)\r\n12 to 14\r\nTransmission\r\nManual\r\nFuel Type\r\nPetrol\r\nEngine\r\n1600 cc\r\nToyota Corolla Altis X Manual 1.6 Price in Pakistan\r\nThe price of Toyota Corolla Altis X Manual 1.6 in Pakistan is PKR 3,909,000. This price of Corolla Altis X Manual 1.6 is ex-factory and does not include freight, taxes and other documentation charges.\r\n\r\nVariant Ex-Factory Price On Road Price\r\nToyota Corolla Altis X Manual 1.6\r\nPKR 3,909,000\r\nGet Corolla Altis X Manual 1.6 On Road Price\r\nToyota Corolla Altis X Manual 1.6 2021 Price | Toyota Corolla Altis X Manual 1.6 2020 Price | Toyota Corolla Altis X Manual 1.6 2018 Price\r\n\r\nToyota Corolla Altis X Manual 1.6 Colors\r\nToyota Corolla Altis X Manual 1.6 is available in 7 different colours - Attitude Black, Bronze Mica, Dorado Gold, Phantom Brown, Silver Metallic, Strong Blue, and Super White\r\n\r\nAttitude Black\r\n\r\nBronze Mica\r\n\r\nDorado Gold\r\n\r\nPhantom Brown\r\n\r\nSilver Metallic\r\n\r\nStrong Blue\r\n\r\nSuper White\r\n\r\nToyota Corolla Altis X Manual 1.6 Specifications & Features\r\nSpecifications\r\nFeatures\r\nSpecifications\r\nDimensions\r\nOverall Length 4620 mmKerb Weight 1275 KGOverall Width 1775 mmBoot Space 470 LOverall Height 1475 mmSeating Capacity 5 personsWheel Base 2700 mmNo. of Doors 5 doorsGround Clearance 175 mm\r\nEngine/ Motor\r\nEngine Type PetrolNo. of Cylinders 4Displacement 1600 ccCylinder Configuration In LineHorse Power 120 HP @ 6000 RPMCompression Ratio 10.0:1Torque 154 Nm @ 5200 RPMValves per Cylinder 4Fuel System Sequential Multiport Fuel InjectionValve Mechanism DOHC 16 Valves with dual VVT-iMax Speed 180 KM/H\r\nTransmission\r\nTransmission Type ManualGearbox 6 - speed\r\nSteering\r\nSteering Type Rack & Pinion with Electronic MotorMinimum Turning Radius 5.4mPower Assisted Electronic Power Steering\r\nSuspension & Brakes\r\nSuspension Front: Macpherson Strut, Rear: Torsion BeamBrakes Front: Ventilated Disc, Rear: Solid Disc\r\nWheels and Tyres\r\nWheel Type Steel Rims with Wheels CapsTyre Size 195/65/R15Wheel Size 15 inSpare Tyre PCD 5 x 100mmSpare Tyre Size 15 in\r\nFuel Economy\r\nMileage City 12 KM/LFuel Tank Capacity 55 LMileage Highway 14 KM/L\r\nFeatures\r\nSafety\r\nNo. of Airbags 2Anti-Lock Braking System (ABS) No. of Seatbelts 5Down Hill Assist Control Immobilizer Hill Start Assist Control Child Lock Traction Control ISOFIX Child Seat Anchors Vehicle Stability Control\r\nExterior\r\nAlloy Wheels Adjustable Headlights Colored Outside Door Handles YesFog Lights Side Mirrors With Indicators DRLs Rear Spoiler Sun Roof / Moon Roof /\r\nInstrumentation\r\nTachometer Multi Info\r\nInfotainment\r\nCD/DVD Player / Front Speakers USB and Auxillary Cable Rear Speakers Display Size 9.0 inRear Seat Entertainment\r\nComfort and Convenience\r\nAir Conditioner Cruise Control Climate Control Driving Modes Rear AC Vents Key Type Keyless entryHeater Keyless Entry Heated Seats Push Start Defogger Central Locking CoolBox Power Door Locks Navigation Power Steering Optional Navigation Power Windows Front Camera Power Mirrors Rear Camera Power Boot Rear Central Control Cup Holders Rear Folding Seat Arm Rest Rear Headrest YesHandbrake Center LeverRear Wiper Interior Lighting Seat Material Type Fabric with manual adjustmentFront Power Outlet Steering Adjustment Rear Power Outlet Steering Switches",
            "discount": "1",
            "disc_value": "15",
            "disc_price": "586350",
            "category": "car",
            "sub_category": "manual",
            "brands": "toyota",
            "price": "3909000",
            "quantity": "16",
            "image": "https://cache1.pakwheels.com/system/car_generation_pictures/5361/original/Corolla-X-Cars-Cropped-Pictures-for-Website.jpg?1606903674"
        },
        {
            "name": "Toyota Corolla Altis Grande X CVT-i 1.8 Beige Interior",
            "vendor": "1",
            "title": "Toyota Corolla Altis Grande X CVT-i 1.8 Beige Interior",
            "slug": "toyota-corolla-altis-grande-x-cvt-i-1.8-beige-interior",
            "description": "MILEAGE (KM/LITER)\r\n12 to 14\r\nTransmission\r\nAutomatic (CVT)\r\nFuel Type\r\nPetrol\r\nEngine\r\n1800 cc\r\nToyota Corolla Altis Grande X CVT-i 1.8 Beige Interior Price in Pakistan\r\nThe price of Toyota Corolla Altis Grande X CVT-i 1.8 Beige Interior in Pakistan is PKR 4,859,000. This price of Corolla Altis Grande X CVT-i 1.8 Beige Interior is ex-factory and does not include freight, taxes and other documentation charges.\r\n\r\nVariant Ex-Factory Price On Road Price\r\nToyota Corolla Altis Grande X CVT-i 1.8 Beige Interior\r\nPKR 4,859,000\r\nGet Corolla Altis Grande X CVT-i 1.8 Beige Interior On Road Price\r\nToyota Corolla Altis Grande X CVT-i 1.8 Beige Interior 2021 Price | Toyota Corolla Altis Grande X CVT-i 1.8 Beige Interior 2020 Price | Toyota Corolla Altis Grande X CVT-i 1.8 Beige Interior 2019 Price | Toyota Corolla Altis Grande X CVT-i 1.8 Beige Interior 2018 Price\r\n\r\nToyota Corolla Altis Grande X CVT-i 1.8 Beige Interior Colors\r\nToyota Corolla Altis Grande X CVT-i 1.8 Beige Interior is available in 8 different colours - Attitude Black, Bronze Mica, Dorado Gold, Graphite Grey, Phantom Brown, Silver Metallic, Strong Blue, and Super White\r\n\r\nAttitude Black\r\n\r\nBronze Mica\r\n\r\nDorado Gold\r\n\r\nGraphite Grey\r\n\r\nPhantom Brown\r\n\r\nSilver Metallic\r\n\r\nStrong Blue\r\n\r\nSuper White\r\n\r\nToyota Corolla Altis Grande X CVT-i 1.8 Beige Interior Specifications & Features\r\nSpecifications\r\nFeatures\r\nSpecifications\r\nDimensions\r\nOverall Length 4620 mmKerb Weight 1275 KGOverall Width 1775 mmBoot Space 470 LOverall Height 1475 mmSeating Capacity 5 personsWheel Base 2700 mmNo. of Doors 5 doorsGround Clearance 170 mm\r\nEngine/ Motor\r\nEngine Type PetrolNo. of Cylinders 4Displacement 1800 ccCylinder Configuration In LineHorse Power 138 HP @ 6400 RPMCompression Ratio 10.0:1Torque 173 Nm @ 4000 RPMValves per Cylinder 4Fuel System Sequential Multiport Fuel InjectionValve Mechanism DOHC 16 Valves with dual VVT-iMax Speed 180 KM/H\r\nTransmission\r\nTransmission Type Automatic (CVT)Gearbox -CVT\r\nSteering\r\nSteering Type Rack & Pinion with Electronic MotorMinimum Turning Radius 5.4mPower Assisted Electronic Power Steering\r\nSuspension & Brakes\r\nSuspension Front: Macpherson Strut, Rear: Torsion BeamBrakes Front: Ventilated Disc, Rear: Solid Disc\r\nWheels and Tyres\r\nWheel Type Alloy wheels with Imported Japanese TyresTyre Size 205/55/R16Wheel Size 16 inSpare Tyre PCD 5 x 100mmSpare Tyre Size 16 in\r\nFuel Economy\r\nMileage City 12 KM/LFuel Tank Capacity 55 LMileage Highway 14 KM/L\r\nFeatures\r\nSafety\r\nNo. of Airbags 2Anti-Lock Braking System (ABS) No. of Seatbelts 5Down Hill Assist Control Immobilizer Hill Start Assist Control Child Lock Traction Control ISOFIX Child Seat Anchors Vehicle Stability Control\r\nExterior\r\nAlloy Wheels Adjustable Headlights Colored Outside Door Handles YesFog Lights Side Mirrors With Indicators DRLs Rear Spoiler Sun Roof / Moon Roof /\r\nInstrumentation\r\nTachometer Multi Info\r\nInfotainment\r\nCD/DVD Player / Front Speakers USB and Auxillary Cable Rear Speakers Display Size 9.0 inRear Seat Entertainment\r\nComfort and Convenience\r\nAir Conditioner Cruise Control Climate Control Driving Modes Rear AC Vents Key Type Keyless entryHeater Keyless Entry Heated Seats Push Start Defogger Central Locking CoolBox Power Door Locks Navigation Power Steering Optional Navigation Power Windows Front Camera Power Mirrors Rear Camera Power Boot Rear Central Control Cup Holders Rear Folding Seat Arm Rest Rear Headrest YesHandbrake Center LeverRear Wiper Interior Lighting Seat Material Type Leather seat with manual adjustmentFront Power Outlet Steering Adjustment Rear Power Outlet Steering Switches",
            "discount": "0",
            "disc_value": "0",
            "disc_price": "0",
            "category": "car",
            "sub_category": "manual",
            "brands": "toyota",
            "price": "4859000",
            "quantity": "51",
            "image": "https://cache1.pakwheels.com/system/car_generation_pictures/5361/original/Corolla-X-Cars-Cropped-Pictures-for-Website.jpg?1606903674"
        },
        {
            "name": "KENWOOD KRF-24457GDMRG TWO DOOR NON INVERTER",
            "vendor": "1",
            "title": "KENWOOD KRF-24457GDMRG TWO DOOR NON INVERTER",
            "slug": "kenwood-krf-24457gdmrg-two-door-non-inverter",
            "description": "Item Condition: New\r\nShipping Info: 24 - 48 Hours\r\nStock Info: Available\r\nwarranty: THREE YEARS COMPRESSOR, ONE YEAR PARTS & SERVICE Colour / Material RED",
            "discount": "1",
            "disc_value": "15",
            "disc_price": "7934.85",
            "category": "fridge",
            "sub_category": "double door",
            "brands": "kenwood",
            "price": "52899",
            "quantity": "84",
            "image": "https://www.mega.pk/items_images/KENWOOD+KRF-24457GDMRG+TWO+DOOR+NON+INVERTER+Price+in+Pakistan%2C+Specifications%2C+Features%2C+Reviews_-_22456.webp"
        },
        {
            "name": "Haier Top Mount Refrigerator 368EBD",
            "vendor": "2",
            "title": "Haier Top Mount Refrigerator 368EBD",
            "slug": "haier-top-mount-refrigerator-368ebd",
            "description": "Features\r\n\r\nFull Electric Solution (FES)\r\nBest Performance\r\nDoor Hinge: Right\r\nFast Cooling\r\nIntelligent Function\r\n\r\n\r\nSpecifications\r\n\r\nTop Mount\r\nR134a Refrigerant\r\nDirect Cool\r\nFree Standing\r\nConventional\r\nGold Color\r\nNo.of Crispers in Fridge: 1\r\nColor of Crispers in Fridge: Transparent\r\nNo.of Shelves in Fridge: 3\r\nType of Shelves in Fridge: Wire\r\nNo.of Shelves in Freezer: 2\r\nNo. of Racks in Fridge Door: 4\r\nNo.of Racks in Freezer Door: 2\r\nNo. of Egg Racks: 2",
            "discount": "1",
            "disc_value": "15",
            "disc_price": "8355",
            "category": "fridge",
            "sub_category": "general",
            "brands": "haier",
            "price": "55700",
            "quantity": "52",
            "image": "https://www.alfatah.com.pk/wp-content/uploads/2020/07/haier-368ebd-refrigerator.jpg"
        },
        {
            "name": "Haier Top Mount Refrigerator 368EPC-W",
            "vendor": "0",
            "title": "Haier Top Mount Refrigerator 368EPC-W",
            "slug": "haier-top-mount-refrigerator-368epc-w",
            "description": "Features\r\n\r\nRight Door Hinge\r\nFast Cooling\r\nTransparent Color of Crispers in Fridge\r\nLighting\r\nIntelligent Function\r\nGlass Shelves\r\n\r\n\r\nSpecifications\r\n\r\nTop Mount\r\nDirect Cool\r\nR134a Refrigerant\r\nFree Standing\r\nNo.of Crispers in Fridge: 1\r\nNo.of Shelves in Fridge: 3\r\nNo.of Shelves in Freezer: 2\r\nNo. of Racks in Fridge Door: 4\r\nNo.of Racks in Freezer Door: 2\r\nNo. of Egg Racks: 2",
            "discount": "1",
            "disc_value": "15",
            "disc_price": "8999.85",
            "category": "fridge",
            "sub_category": "double door",
            "brands": "haier",
            "price": "59999",
            "quantity": "32",
            "image": "https://www.alfatah.com.pk/wp-content/uploads/2021/07/Untitled-1-5.png"
        },
        
    ]

class Command(BaseCommand):
    # Show this when the user types help
    help = "Create Role and its permissions"

    # A command must define handle()
    def handle(self, *args, **options):
        for item in PRODUCTS:
            name= item.get('name')
            title= item.get('title')
            slug= item.get('slug')
            description= item.get('description')
            discount= item.get('discount')
            disc_value= Decimal(item.get('disc_value')).quantize(Decimal('.01'))
            disc_price= Decimal(item.get('disc_price')).quantize(Decimal('.01'))
            category= item.get('category')
            sub_category= item.get('sub_category')
            brands= item.get('brands')
            price= Decimal(item.get('price')).quantize(Decimal('.01'))
            quantity= int(item.get('quantity'))
            image= item.get('image')
            cat_img = "no_image.jpg"
            brand, create= Brand.objects.get_or_create(title = brands)
            user_pk = random.randint(1,3)
            year = random.randint(2019,2022)
            user = UserAccount.objects.get(pk=user_pk)
            cat = Category.objects.get(title = category)
            if cat is not None:
                sub, create = SubCategory.objects.get_or_create(category= cat, title= sub_category)
                if user is not None:
                    
                    product, create = Product.objects.get_or_create(
                        name =name,
                        vendor = user,
                        title =title,
                        slug =slug,
                        description =description,
                        discount =discount,
                        disc_value =disc_value,
                        disc_price =disc_price,
                        category =cat,
                        sub_category =sub,
                        brands =brand,
                        year= year,
                        price =price,
                        quantity =quantity,
                        image =image,
                    )
                    product.save()
                    print (product)
                else:
                    obj = Category.objects.create(title = category, image= cat_img)
                    obj.save()
                    sub, create = SubCategory.objects.get_or_create(category= obj, title= sub_category)
                    if user is not None: 
                        product, create = Product.objects.get_or_create(
                            name =name,
                            vendor = user,
                            title =title,
                            slug =slug,
                            description =description,
                            discount =discount,
                            disc_value =disc_value,
                            disc_price =disc_price,
                            category =obj,
                            sub_category =sub,
                            brands =brand,
                            price =price,
                            quantity =quantity,
                            image =image,
                        )
                        product.save()
                        print (product)