# Generated by Django 4.0.4 on 2022-08-24 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
